#!/bin/bash
# Script used for compiling main.tex, a file created by: 
# lucasribeiro@ufrj.br / Federal University of Rio de Janeiro


# Instructions for compiling on linux( Tested on Ubuntu 10.04 ):
# 1) Open terminal ( crtl + alt + control )
# 2) Navegate to the folder where compileTex.sh is in using the command:
# $ cd <path-to-compileTex.sh>
# Where <path-to-compileTex.sh> could be ~/MyFiles/latex resulting in the command:
# $ cd ~/MyFiles/latex
# 3) Now that you are in folder where compileTex.sh resides, you must change the permission
# of the file, so that you can execute it. To do that you can use the command chmod. For example
# use like this:
# $ sudo chmod 777 compileTex.sh
# 4) Now you can run the script by doing this:
# $ ./compileTex.sh
# 5) The pdf generated will be at same folder as script file compileTex.sh (root folder)
# 
# Obs.: To clean up all files generated by latex, use the parameter clean as:
# $ ./compileTex.sh clean


# Vide http://tex.stackexchange.com/questions/121383/how-does-the-latex-compile-chain-work-exactly

# BEG - Functions declarations
function checkCompilation {
  if [[ "$1" != 0 ]]; then
    echo "Fail to compile $2"
    exit $$1
  fi
}
# BEG - Functions declarations



# Defining variables
MAIN_TEX="main"
OUTPUT_DIR="obj"
texStuffFolder=./latex-stuff
bibtexFolder=./pos-textual
bibtexFile="referencias"
bibtexStyle="abnt-ufrgs"



############ START SCRIPTS (clean and compilation) #############

# To clean ${OUTPUT_DIR} files, to use it just run
#$./compileTex.sh clean
if [ "clean" == "$1" ]; then
   rm -r ./${OUTPUT_DIR}
   exit 0
fi



# BEG - Setting search path
export TEXINPUTS=${TEXINPUTS}:.:${texStuffFolder}
export BIBINPUTS=${BIBINPUTS}:${OUTPUT_DIR}/${MAIN_TEX}.aux:${bibtexFolder}/$bibtexFile.bib:${texStuffFolder}/$bibtexStyle.bst
export TEXMFOUTPUT=${TEXMFOUTPUT}:${OUTPUT_DIR}
# END - Setting searching path

echo "Compiling $MAIN_TEX.tex"



# Checks whether is there a directory named ${OUTPUT_DIR} or not.
# In case does not exist, create it.
if [ ! -d ${OUTPUT_DIR} ]; then
  mkdir ${OUTPUT_DIR}
fi



# Compiling with latex
pdflatex -halt-on-error -output-directory=./${OUTPUT_DIR} $MAIN_TEX.tex
checkCompilation $? $MAIN_TEX.tex

# Run bibtex in the ${OUTPUT_DIR} directory
bibtex ${OUTPUT_DIR}/$MAIN_TEX
checkCompilation $? $MAIN_TEX.tex

# Compiling with latex again to get bibliography and cross-references
pdflatex -halt-on-error -output-directory=./${OUTPUT_DIR} $MAIN_TEX.tex
checkCompilation $? $MAIN_TEX.tex

# Compiling with latex again to get citations
pdflatex -halt-on-error -output-directory=./${OUTPUT_DIR} $MAIN_TEX.tex
checkCompilation $? $MAIN_TEX.tex

mv ./${OUTPUT_DIR}/$MAIN_TEX.pdf .

echo "Done! Look for $MAIN_TEX.pdf in the root directory"
exit 0

